baseURL = "https://johanacardona.com/"
title = "un blog?"
theme = "harbor"
languageCode = "es"
DefaultContentLanguage = "es"

[Author]
  name = "Daniel"

[params]
  customCSS = ["/css/custom.css"]
  mainSections = ["post"]

[params.logoText]
  value = "Home"

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "page/about/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "page/search/"
  weight = 3
