baseURL = "https://johanacardona.com/"
languageCode = "es-co"
title = "a blog?"
theme = "harbor"

[Author]
  name = "Daniel"

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3
