baseURL = "https://nomennescio1.github.io/un-blog/"
title = "un blog?"
theme = "harbor"
languageCode = "es"
DefaultContentLanguage = "es"

[Author]
  name = "Daniel"

[permalinks]
	page = "/:filename/"

[outputs]
  section = ["JSON", "HTML"]

[params]
  customCSS = ["/css/custom.css"]
  mainSections = ["post"]

[params.logoText]
  value = "Home"

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3
